### ISSUE TITLE
Sorting patients based on WGCNA module

### ISSUE THREAD

**Issue by kphelan13** [seiboldlab/SingleCell_IL13#1]
Hi, I am trying to perform a similar analysis where I want to use a specific module to sort patient samples from RNA-seq. I am following your code but it is unclear to me how you sorted your samples based on the "skyblue" module. It seems that in your "Analysis" script the Th2 status was already labeled in your phenotype file, so I am curious as to how you assigned this status to samples based on the WGCNA.

Thanks!

Kieran

**Comment by ndjaxon** [comment]
Hi Kieran,

Sorry that's not in there. The dichotomous "type 2 high" and "type 2 low" assignments we used were based on hierarchical clustering of samples into K = 2 groups based on expression of the genes in the skyblue module. Specifically (assuming you've got the count matrix loaded, GALA_vst), I first created a distance matrix of the genes in the skyblue module (the gene2module table can be imported from data/695.res.WGCNA.gene2module.with.cor.txt). Then I clustered the genes based on these distances with hclust and cut the tree based on the deepest split. Here's an example:

`dists<-dist(t(GALA_vst)[,gene2module$gene[which(gene2module$module == "skyblue")]], 
	method = 'manhattan')
clusts<-hclust(dists,method='ward.D')
'type2_status<-cutree(clusts, k = 2)`

I can't seem to find the original code for the division used in the paper right now, so I can't say that these were the methods (manhattan for the distance matrix or ward.D for hclust) I used here. Typically, I try several methods and then determine which clustering best appears to capture "high" and "low" groups visually.

If you would prefer to have a continuous measure of Type 2 expression by which you can sort patients, you can also calculate eigengene expression for the skyblue module, which provides an expression score or weight for each subject based on their relative expression for that network of genes. The code for this is in lines 161-163 of the 08_WGCNA_gala.R script. Eigenegenes for all the modules based on this code are stored in data/695.res.WGCNA.ME.txt.

Hope this helps,

Nathan

**Comment by kphelan13** [comment]
Thanks Nathan, this clears it up. I actually went ahead with the Eigenvalue method on my own and had some success with my own data. Thanks for your help with the code/method.

Kieran
